feat(nx-python): follow all groups with dep graph
lucasvieirasilva/nx-plugins pull request #22
Opened 2023-01-19 21:22 UTC by niall-mediasuite

Ensures that the dependency graph follows all arbitrary pip dependency groups.

## Current Behavior

Currently the dependency graph only respects the main depdencies and the dev dependency group. This expands it to support any arbitrary groups like poetry supports. e.g. `tool.poetry.group.example_group.dependencies`

## Expected Behavior

Any dependencies added to custom groups appear in the dependency graph.

## Related Issue(s)

None

2023-01-20 16:22 UTC, lucasvieirasilva requested changes
I believe you also need to check the code coverage.

2023-01-22 20:47 UTC, niall-mediasuite commented
Hi @lucasvieirasilva I have added a test to the `add` executor to exersize this code path.

2023-01-23 13:40 UTC, lucasvieirasilva commented
> Hi @lucasvieirasilva I have added a test to the `add` executor to exersize this code path.

Hi @niall-mediasuite, I did a comment in the code implementation, could you check, please?

2023-01-23 20:18 UTC, niall-mediasuite commented on packages/nx-python/src/graph/dependency-graph.ts
> +    if (isDep) return true;
Yeah sorry I moved this in the previous changes. Forgot to mention that I had resolved this. This was my indention when writing the code but put the check in the wrong place.

2023-01-23 20:19 UTC, niall-mediasuite commented on packages/nx-python/src/graph/dependency-graph.ts
> +    if (isDep) return true;
Looks like that change didn't make its way in. I'll update it now.

2023-01-23 20:21 UTC, niall-mediasuite commented on packages/nx-python/src/graph/dependency-graph.ts
> +    if (isDep) return true;
I have now updated this.

2023-01-24 10:15 UTC, lucasvieirasilva commented on packages/nx-python/src/graph/dependency-graph.ts
> +    if (isDep) return true;
Many thanks

2023-01-24 10:16 UTC, lucasvieirasilva commented
@niall-mediasuite I did some changes in the GitHub Actions CI permissions, could sync your branch with the repo `main` please?

2023-01-24 23:29 UTC, niall-mediasuite commented
Updated with latest commits from main.

2023-01-25 15:53 UTC, lucasvieirasilva commented
@niall-mediasuite sorry about that, I was using GitHub actions to perform the Code Coverage report, and looks like there are some problems with forked repositories, so, I've changed the action to use Coveralls, then I tested forking the repo from a different account and raising a PR, everything seems works fine now, could you sync your branch again, hope that is the last time

2023-01-25 19:58 UTC, niall-mediasuite commented
No problem. I know what its like doing CI work. I have updated the branch.

2023-01-25 21:09 UTC, lucasvieirasilva approved these changes

2023-01-25 21:09 UTC, merged